# Cloud Run deployment configuration
# This file is used when deploying to Google Cloud Run

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
  name: keystone-compartido
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/keystone-compartido-app/keystone-compartido
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        env:
        - name: NODE_ENV
          value: "production"
        # Add your environment variables here
        # - name: VITE_API_BASE_URL
        #   value: "https://your-api-domain.com"